contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
watch = true
paginate = 1000
buildDrafts = false
canonifyURLs = true
metaDataFormat = "toml"
defaultContentLanguage = "zh-CN"
LanguageCode = "zh-CN"
HasCJKLanguage = true
baseURL = "www.iinrs.com"

[taxonomies]
  series = "series"

[params]
  SiteLogo = "*如实尚品*"
  SiteTitle = "「如实尚品」不一样的专业人工导购、精选优质商品、特价、折扣、秒杀、返利、隐藏优惠卷的购物网站"
  description = "「如实尚品」您再也不需要从海量商品中挑选满意宝贝而忧心了！这里有专业的淘金手为您精选出最优质、最实惠的产品！相信专业，就在如实"
  notice = "在如实有任何的问题，都可以通过微信与我们取得联系。"
  copyright = "CopyRight © 如实尚品 版权所有"